### PR TITLE
Change color label navigation bar

### LINKED ISSUE #7: Change color of the menu bar navigation
When we click on the menu bar at the top left, we can't see the text because it has the same color as the background. So maybe it could be great to add a white text.
image

### PR DESCRIPTION
**Pull request by jvondermarck**
Change line 30 from black color to white. 
Fix #7

### CODE REVIEW

**Comment by brianreville** [comment]
@jvondermarck  are using dark mode on your pc/ laptop

When I run on my machine this is the color scheme I get

image

**Comment by jvondermarck** [comment]
Oh yes right, I'm using dark mode. I didn't know that the application depended on the  white or black mode.
So do you want me to change the color of the label to another one to be able to run the application on dark and white mode with a visible label color ?

**Comment by brianreville** [comment]
@jvondermarck No that might be a bit much for a first issue as would be required to set up access permissions for the various OS to see whether they were using dark mode or not, might make a note that the application is currently optimized for light mode.

**Comment by jvondermarck** [comment]
@brianreville is that okay for you ? By adding the light mode for windows users, I run the application with the light mode by still having dark mode on my computer.

**Pull request merged**
